#!/usr/bin/env python3
"""
老王的数据修复脚本 - 为现有产品添加subcategory字段
"""

import json
import re
import os
from pathlib import Path
from typing import Dict, Any

class SubcategoryFixer:
    """老王的子分类修复器"""

    def __init__(self, data_dir='src/data'):
        self.data_dir = Path(data_dir)
        self.processed_count = 0
        self.error_count = 0

    def extract_subcategory(self, name: str, brand: str) -> str:
        """从产品名称中提取子分类"""
        name_lower = name.lower()
        brand_lower = brand.lower()

        name_lower = name_lower.replace('é', 'e').replace('É', 'E').replace('ô', 'o').replace('û', 'u').replace('à', 'a').replace('ç', 'c').replace('è', 'e').replace('ê', 'e').replace('î', 'i').replace('ï', 'i').replace('ù', 'u').replace('ü', 'u').replace('ö', 'o').replace('ä', 'a').replace('ñ', 'n')

        if 'chanel' in name_lower:
            brand_lower = 'chanel'
        elif 'dior' in name_lower:
            brand_lower = 'dior'
        elif 'gucci' in name_lower:
            brand_lower = 'gucci'
        elif 'ysl' in name_lower or 'yves saint laurent' in name_lower:
            brand_lower = 'ysl'
        elif 'hermes' in name_lower:
            brand_lower = 'hermes'
        elif 'prada' in name_lower:
            brand_lower = 'prada'
        elif 'bottega' in name_lower or 'bv' in name_lower:
            brand_lower = 'bottega veneta'
        elif 'celine' in name_lower:
            brand_lower = 'celine'
        elif 'goyard' in name_lower:
            brand_lower = 'goyard'
        elif 'loewe' in name_lower:
            brand_lower = 'loewe'
        elif 'balenciaga' in name_lower:
            brand_lower = 'balenciaga'
        elif 'miumiu' in name_lower:
            brand_lower = 'miumiu'
        elif 'fendi' in name_lower:
            brand_lower = 'fendi'
        elif 'burberry' in name_lower:
            brand_lower = 'burberry'
        elif 'loro piana' in name_lower:
            brand_lower = 'loro piana'
        elif 'givenchy' in name_lower:
            brand_lower = 'givenchy'

        # 品牌特定的子分类匹配规则
        subcategory_rules = {
            'chanel': {
                'mini flap': 'mini-flap',
                'classic flap': 'classic-flap',
                'flapbag': 'classic-flap',
                'flap bag': 'classic-flap',
                'flap': 'classic-flap',
                '2.55': '2-55',
                '25 small': '2-55',
                '25 mini': '2-55',
                '25 medium': 'classic-flap',
                '25 large': 'classic-flap',
                '25 handbag': 'classic-flap',
                '19': 'classic-flap',
                '19 handbag': 'classic-flap',
                'boy': 'boy-bag',
                'backpack': 'backpack',
                'wallet on chain': 'wallet-on-chain',
                'shopping bag': 'shopping-bag',
                'tote': 'tote',
                'small tote': 'tote',
                'shoulder bag': 'shoulder-bag',
                'crossbody': 'crossbody',
                'pouch': 'pouch',
                'zipped pouch': 'pouch',
                'clutch': 'clutch',
                'mini': 'mini-bag',
                'belt bag': 'belt-bag',
                'evening': 'evening-bag',
                '11.12': 'classic-flap',
                'coco': 'classic-flap',
                'camera case': 'crossbody',
                'vanity': 'vanity',
                'vanity with chain': 'vanity',
                'large vanity': 'vanity',
                'small wallet': 'wallet-on-chain',
                'large zipped': 'pouch',
                'small shopping': 'shopping-bag',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'small flap': 'mini-flap',
                'medium flap': 'classic-flap',
                'large flap': 'classic-flap',
                'new classic': 'classic-flap',
                'reissue': '2-55',
                'woc': 'wallet-on-chain',
                'bucket': 'crossbody',
                'hobo': 'shoulder-bag',
                'bag on chain': 'wallet-on-chain',
                'chain bag': 'wallet-on-chain',
                'handle bag': 'shoulder-bag',
                'top handle': 'shoulder-bag',
                'classic handbag': 'classic-flap',
                'large classic': 'classic-flap',
                'small classic': 'mini-flap',
                'medium classic': 'classic-flap',
                'maxi flap': 'classic-flap',
                'jumbo flap': 'classic-flap',
                'ultra flap': 'classic-flap',
                'tweed flap': 'classic-flap',
                'stitch flap': 'classic-flap',
                'double flap': 'classic-flap',
                'single flap': 'classic-flap',
                'mademoiselle': 'classic-flap',
                'premiere': 'classic-flap',
                'timeless': 'classic-flap',
                'essentiel': 'classic-flap',
                'trendy cc': 'classic-flap',
                'urban spirit': 'backpack',
                'spirit': 'backpack',
                'classic backpack': 'backpack',
                'travel backpack': 'backpack',
                'school backpack': 'backpack',
                'shopping tote': 'tote',
                'canvas tote': 'tote',
                'deauville': 'tote',
                'grand shopping': 'tote',
                'beach tote': 'tote',
                'cabriolet': 'shoulder-bag',
                'graceful': 'shoulder-bag',
                'urban': 'shoulder-bag',
                'casual': 'shoulder-bag',
                'sporty': 'shoulder-bag',
                'duma': 'backpack',
                'cruise': 'tote',
                'seasonal': 'shoulder-bag',
                'resort': 'tote',
                'spring': 'shoulder-bag',
                'summer': 'tote',
                'fall': 'shoulder-bag',
                'winter': 'shoulder-bag',
                'holiday': 'evening-bag',
                'limited': 'shoulder-bag',
                'edition': 'shoulder-bag',
                'exclusive': 'shoulder-bag',
                'special': 'shoulder-bag',
                'unique': 'shoulder-bag',
                'rare': 'shoulder-bag',
                'vintage': 'classic-flap',
                'pre-owned': 'classic-flap',
                'authentic': 'classic-flap',
                'certified': 'classic-flap',
                'genuine': 'classic-flap',
                'real': 'classic-flap',
                'replica': 'classic-flap',
                'copy': 'classic-flap',
                'fake': 'classic-flap',
                'handbag': 'classic-flap',
                'medium handbag': 'classic-flap',
                'large handbag': 'classic-flap',
                'small handbag': 'mini-flap',
                'bowling': 'shoulder-bag',
                'gst': 'tote',
                'tmall elf': 'mini-bag',
                'box bag': 'clutch',
                'small box': 'clutch',
                'kelly': 'shoulder-bag',
                'bow': 'shoulder-bag',
                'phone holder': 'clutch',
                'flap phone': 'clutch',
                'bag on 25': 'classic-flap',
                'cambon': 'tote',
                'waist bag': 'belt-bag',
                'minaudiere': 'evening-bag',
                'tea box': 'evening-bag',
                'ice cream': 'evening-bag',
                'camera bag': 'crossbody',
                'messanger': 'crossbody',
                'messenger': 'crossbody',
                'baguette': 'shoulder-bag',
                'heart': 'mini-bag',
                'sneaker': 'clutch',
                'slingback': 'clutch',
                'long box': 'pouch',
                '24p': 'classic-flap',
                '24c': 'classic-flap',
                '22s': 'classic-flap',
                'zipped coin': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'zip up': 'shoulder-bag',
                'ballet': 'clutch',
                'trainer': 'clutch',
                'loafer': 'clutch',
                'mary jane': 'clutch',
                'rain boot': 'clutch',
                'flats': 'clutch',
                'shoes': 'clutch',
                'boots': 'clutch'
            },
            'louis vuitton': {
                'neverfull': 'neverfull',
                'speedy': 'speedy',
                'keepall': 'keepall',
                'carryall': 'carryall',
                'onthego': 'onthego',
                'neverwoof': 'neverwoof',
                'coussin': 'coussin',
                'dauphine': 'dauphine',
                'petite malle': 'petite-malle',
                'capucines': 'capucines',
                'multi pocket': 'multi-pocket',
                'tote': 'tote',
                'backpack': 'backpack',
                'crossbody': 'crossbody',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'madeleine': 'shoulder-bag',
                'squire': 'crossbody',
                'nice': 'clutch',
                'high rise': 'shoulder-bag',
                'boulogne': 'shoulder-bag',
                'diane': 'shoulder-bag',
                'vendome': 'shoulder-bag',
                'vendôme': 'shoulder-bag',
                'neonoé': 'crossbody',
                'neo noe': 'crossbody',
                'neo': 'crossbody',
                'noe': 'crossbody',
                'neono': 'crossbody',
                'neo no': 'crossbody',
                'hobo metis': 'crossbody',
                'hobo': 'shoulder-bag',
                'metis': 'crossbody',
                'saint germain': 'shoulder-bag',
                'vagabond': 'shoulder-bag',
                'express': 'crossbody',
                'vers': 'crossbody',
                'versatile': 'crossbody',
                'lineup': 'clutch',
                'lock and walk': 'crossbody',
                'victorie': 'crossbody',
                'neo': 'crossbody',
                'all around': 'tote',
                'hobo metis': 'crossbody',
                'easy pouch': 'clutch',
                'tag me': 'clutch',
                'hang on': 'clutch',
                'multipass': 'wallet-on-chain',
                'vanity chain': 'vanity',
                'phone pouch': 'clutch',
                'pocket organizer': 'wallet-on-chain',
                'cosmetic': 'pouch',
                'lipstick': 'pouch',
                'card holder': 'wallet-on-chain',
                'passport': 'wallet-on-chain',
                'sneaker': 'clutch',
                'trainer': 'clutch',
                'loafer': 'clutch',
                'high heel': 'clutch',
                'ballerina': 'clutch',
                'mule': 'clutch',
                'sneakerina': 'clutch',
                'frontrow': 'clutch',
                'lagoon': 'clutch',
                'time out': 'clutch',
                '6am': 'clutch',
                'major': 'clutch',
                'low key': 'shoulder-bag',
                'baia': 'shoulder-bag',
                'kirigami': 'wallet-on-chain',
                'vanity pm': 'vanity',
                'new wave': 'shoulder-bag',
                'favorite': 'shoulder-bag',
                'bella': 'mini-bag',
                'neonoé': 'crossbody',
                'neo noe': 'crossbody',
                'montsouris': 'backpack',
                'monsouri': 'backpack',
                'tiny camera': 'crossbody',
                'odyssee': 'shoulder-bag',
                'carry it': 'tote',
                'escape': 'backpack',
                'ever more': 'shoulder-bag',
                'blossom': 'shoulder-bag',
                'off duty': 'shoulder-bag',
                'atlantis': 'shoulder-bag',
                'altantis': 'shoulder-bag',
                'nova': 'shoulder-bag',
                'again': 'shoulder-bag',
                'catchy': 'shoulder-bag',
                'fan': 'clutch',
                'fold me': 'pouch',
                'duo': 'shoulder-bag',
                'bundle': 'clutch',
                'ellipse': 'shoulder-bag',
                'boundless': 'tote',
                'hand it all': 'tote',
                'cookie': 'mini-bag',
                'petit palais': 'tote',
                'grand palais': 'tote',
                'sunset': 'shoulder-bag',
                'anytime': 'shoulder-bag',
                'the drop': 'shoulder-bag',
                'soho': 'shoulder-bag',
                'hide away': 'clutch',
                'marellini': 'mini-bag',
                'slouchy': 'shoulder-bag',
                'biker': 'shoulder-bag',
                'why knot': 'shoulder-bag',
                'rivage': 'shoulder-bag',
                'envelope': 'clutch',
                'bloom': 'shoulder-bag',
                'on my side': 'shoulder-bag',
                'varenne': 'shoulder-bag',
                'dopp kit': 'pouch',
                'flore': 'clutch',
                'soft polochon': 'shoulder-bag',
                'orsay': 'shoulder-bag',
                'piano': 'shoulder-bag',
                'mezzo': 'shoulder-bag',
                'vain': 'shoulder-bag',
                'muria': 'shoulder-bag',
                'backup': 'backpack',
                'let go': 'shoulder-bag',
                'just in case': 'clutch',
                'vibe': 'shoulder-bag',
                'papillon': 'shoulder-bag',
                'croissant': 'shoulder-bag',
                'oxford': 'clutch',
                'lock & go': 'crossbody',
                'excursion': 'shoulder-bag',
                'hide and seek': 'clutch',
                'bagatelle': 'shoulder-bag',
                'sac sport': 'tote',
                'beaubourg': 'shoulder-bag',
                'hold me': 'shoulder-bag',
                'bandouliere': 'crossbody',
                'twinny': 'shoulder-bag',
                'opera': 'shoulder-bag',
                'buci': 'shoulder-bag',
                'trianon': 'shoulder-bag',
                'tilsitt': 'shoulder-bag',
                'pop my heart': 'clutch',
                'wapity': 'pouch',
                'gracefull': 'tote',
                'buggy': 'shoulder-bag',
                'surene': 'shoulder-bag',
                'papillon bb': 'mini-bag',
                'le 5 a 7': 'shoulder-bag',
                'bea': 'shoulder-bag',
                'lock &': 'crossbody',
                'vintage monogram': 'tote',
                'denim': 'tote',
                'slingbag': 'crossbody',
                'messenger': 'crossbody',
                'christopher': 'backpack',
                'steamer': 'crossbody',
                'all in': 'carryall',
                'baggy': 'tote',
                'passport cover': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'magnetic card holder': 'wallet-on-chain',
                'recto verso': 'wallet-on-chain',
                'trocadero': 'wallet-on-chain',
                'wearable wallet': 'wallet-on-chain',
                'delta': 'crossbody',
                'east west': 'carryall',
                'soft 30': 'speedy',
                'speedy soft': 'speedy',
                'on the go': 'onthego',
                'loop': 'crossbody',
                'twist': 'shoulder-bag',
                'cluny': 'shoulder-bag',
                'lockme': 'shoulder-bag',
                'metis': 'crossbody',
                'palermo': 'tote',
                'galliera': 'tote',
                'noe': 'crossbody',
                'alma': 'shoulder-bag',
                'brera': 'shoulder-bag',
                'marignan': 'crossbody',
                'saumur': 'crossbody',
                'runner': 'crossbody',
                'pochette': 'clutch',
                'mini pochette': 'clutch',
                'key pouch': 'wallet-on-chain',
                'clémence': 'wallet-on-chain',
                'insolite': 'wallet-on-chain',
                'galliano': 'tote',
                'valmy': 'crossbody',
                'bosphore': 'crossbody',
                'musette': 'crossbody',
                'vavin': 'shoulder-bag',
                'scottie': 'crossbody',
                'deauville': 'tote',
                'cabas': 'tote',
                'kensington': 'tote',
                'louise': 'shoulder-bag',
                'roland garros': 'crossbody',
                'paris': 'shoulder-bag',
                'blois': 'crossbody',
                'danube': 'crossbody',
                'tulum': 'crossbody',
                'besace': 'crossbody',
                'stresa': 'tote',
                'venice': 'shoulder-bag',
                'portobello': 'tote',
                'trevi': 'tote',
                'palma': 'crossbody',
                'thames': 'tote',
                'hampton': 'tote',
                'manhattan': 'tote',
                'catalina': 'tote',
                'saint cloud': 'crossbody',
                'cannes': 'clutch',
                'cigarette': 'clutch',
                'trousse': 'clutch',
                'chaos': 'clutch',
                'chapelier': 'crossbody',
                'gibciere': 'crossbody',
                'fleur': 'clutch',
                'louis': 'shoulder-bag',
                'cartouchiere': 'crossbody',
                'bucket': 'crossbody',
                'bento': 'crossbody',
                'lockit': 'shoulder-bag',
                'mahina': 'tote',
                'monogram eclipse': 'backpack',
                'avenue': 'crossbody',
                'hollywood': 'shoulder-bag',
                'epi': 'shoulder-bag',
                'taiga': 'backpack',
                'nomade': 'shoulder-bag',
                'damier': 'tote',
                'azur': 'tote',
                'graphite': 'backpack',
                'infini': 'shoulder-bag',
                'girolata': 'crossbody',
                'pallas': 'shoulder-bag',
                'marceau': 'crossbody',
                'virgil': 'tote',
                'off-white': 'tote',
                'archlight': 'crossbody',
                'arc': 'crossbody',
                'go-14': 'shoulder-bag',
                's-lock': 'shoulder-bag',
                'avenue sling': 'crossbody',
                'city keepall': 'keepall',
                'soft trunk': 'keepall',
                'trunk': 'keepall',
                'mini trunk': 'keepall',
                'vertical trunk': 'keepall',
                'side trunk': 'keepall',
                'city steamer': 'crossbody',
                'steamer backpack': 'backpack',
                'bumbag': 'belt-bag',
                'discovery': 'backpack',
                'outdoor': 'backpack',
                'laptop': 'backpack',
                'palm springs': 'backpack',
                'springs': 'backpack',
                'cruise': 'crossbody',
                'world tour': 'tote',
                'charm': 'clutch',
                'dice': 'clutch',
                'fleur de monogram': 'clutch',
                'malle': 'petite-malle',
                'petite boite': 'petite-malle',
                'box': 'petite-malle',
                'coffret': 'petite-malle',
                'jewelry': 'clutch',
                'watch': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'tie': 'clutch',
                'cufflinks': 'clutch',
                'money clip': 'wallet-on-chain',
                'card case': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'change purse': 'wallet-on-chain',
                'id holder': 'wallet-on-chain',
                'luggage tag': 'wallet-on-chain',
                'name tag': 'wallet-on-chain',
                'travel': 'keepall',
                'weekend': 'keepall',
                'carry on': 'keepall',
                'business': 'keepall',
                'document': 'keepall',
                'briefcase': 'keepall',
                'portefeuille': 'wallet-on-chain',
                'zippy': 'wallet-on-chain',
                'insolite': 'wallet-on-chain',
                'clemence': 'wallet-on-chain',
                'curieuse': 'wallet-on-chain',
                'koala': 'wallet-on-chain',
                'lockmini': 'wallet-on-chain',
                'morgan': 'wallet-on-chain',
                'multicles': 'wallet-on-chain',
                'pince': 'wallet-on-chain',
                'porte-documents': 'keepall',
                'porte-monnaie': 'wallet-on-chain',
                'porte-cartes': 'wallet-on-chain',
                'porte-clefs': 'wallet-on-chain',
                'travel organizer': 'keepall',
                'packing cube': 'keepall',
                'garment bag': 'keepall',
                'suitcase': 'keepall',
                'duffel': 'keepall',
                'cabin': 'keepall',
                'check-in': 'keepall',
                'wheel': 'keepall',
                'horizon': 'keepall',
                'pegase': 'keepall',
                'trolley': 'keepall',
                'valise': 'keepall',
                'hard case': 'keepall',
                'soft case': 'keepall',
                'luggage': 'keepall',
                'baggage': 'keepall'
            },
            'dior': {
                'lady dior': 'lady-dior',
                'saddle': 'saddle',
                'book tote': 'book-tote',
                'miss dior': 'miss-dior',
                'dioriviera': 'dioriviera',
                'caro': 'caro',
                'bobby': 'bobby',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'backpack': 'backpack',
                'chrono': 'clutch',
                'ribbon': 'clutch',
                'lingot': 'shoulder-bag',
                'briefcase': 'shoulder-bag',
                'sneaker': 'clutch',
                'my dior': 'mini-bag',
                'my tender': 'mini-bag',
                'top handle': 'shoulder-bag',
                'medaillon': 'classic-flap',
                'flap bag': 'classic-flap',
                '30 montaigne': 'shoulder-bag',
                'montaigne': 'shoulder-bag',
                'camp': 'tote',
                'gallop': 'crossbody',
                'voyage': 'tote',
                'diormotion': 'backpack',
                'diorcamp': 'tote',
                'diorride': 'crossbody',
                'walk': 'crossbody',
                'roll': 'tote',
                'star': 'clutch',
                'moon': 'clutch',
                'cannage': 'lady-dior',
                'oblique': 'tote',
                'diorissimo': 'shoulder-bag',
                'issimo': 'shoulder-bag',
                'artisan': 'shoulder-bag',
                'granville': 'tote',
                'panarea': 'tote',
                'palm springs': 'tote',
                'st tropez': 'tote',
                'beach': 'tote',
                'pool': 'tote',
                'lounge': 'tote',
                'cocotte': 'clutch',
                'toujours': 'shoulder-bag',
                'malice': 'clutch',
                'amphi': 'clutch',
                'lucky': 'clutch',
                'tribal': 'clutch',
                'ganse': 'clutch',
                'revolte': 'crossbody',
                'trotter': 'tote',
                'minitrotter': 'crossbody',
                'rendez vous': 'shoulder-bag',
                'diorama': 'shoulder-bag',
                'slim': 'shoulder-bag',
                'frame': 'clutch',
                'micro': 'clutch',
                'ultra': 'clutch',
                'pouch': 'pouch',
                'zip pouch': 'pouch',
                'card holder': 'wallet-on-chain',
                'wallet': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'small wallet': 'wallet-on-chain',
                'billfold': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'money clip': 'wallet-on-chain',
                'card case': 'wallet-on-chain',
                'id holder': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'jewelry box': 'clutch',
                'watch case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'belt': 'belt-bag',
                'suspenders': 'belt-bag',
                'shoes': 'clutch',
                'boots': 'clutch',
                'sandals': 'clutch',
                'sneakers': 'clutch',
                'handbag': 'shoulder-bag',
                'mini bag': 'mini-bag',
                'medium bag': 'shoulder-bag',
                'large bag': 'tote',
                'bag': 'shoulder-bag',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'bridal': 'evening-bag',
                'formal': 'evening-bag',
                'occasion': 'evening-bag',
                'party': 'evening-bag',
                'wedding': 'evening-bag'
            },
            'hermes': {
                'birkin': 'birkin',
                'kelly': 'kelly',
                'constance': 'constance',
                'lindy': 'lindy',
                'bolide': 'bolide',
                'picotin': 'picotin',
                'garden party': 'garden-party',
                'tote': 'tote',
                'hac a dos': 'backpack',
                'hac': 'backpack',
                '24/24': 'shoulder-bag',
                'della cavalleria': 'mini-bag',
                'roulis': 'shoulder-bag',
                'herbag': 'shoulder-bag',
                'maillon': 'wallet-on-chain',
                'neo garden': 'tote',
                'kelly elan': 'shoulder-bag',
                'kelly doll': 'mini-bag',
                'constance elan': 'shoulder-bag',
                'constance to go': 'wallet-on-chain',
                'kelly to go': 'wallet-on-chain',
                'bearn': 'wallet-on-chain',
                'jige': 'clutch',
                'oasis': 'clutch',
                'miss': 'clutch',
                'match': 'clutch',
                'oran': 'clutch',
                'depart': 'clutch',
                'bouncing': 'clutch',
                'sandal': 'clutch',
                'sneaker': 'clutch',
                'slip-on': 'clutch',
                'shawl': 'clutch',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'backpack': 'backpack',
                'crossbody': 'crossbody',
                'alice': 'shoulder-bag',
                'amazone': 'crossbody',
                'argile': 'shoulder-bag',
                'astrologie': 'clutch',
                'atelier': 'shoulder-bag',
                'balade': 'crossbody',
                'barenia': 'shoulder-bag',
                'bastia': 'wallet-on-chain',
                'berline': 'shoulder-bag',
                'bosphore': 'crossbody',
                'brides de gala': 'clutch',
                'cadenas': 'shoulder-bag',
                'calvi': 'wallet-on-chain',
                'cannes': 'clutch',
                'caravan': 'shoulder-bag',
                'cargo': 'shoulder-bag',
                'carrousel': 'shoulder-bag',
                'castle rock': 'shoulder-bag',
                'chaîne d\'ancre': 'clutch',
                'chalice': 'shoulder-bag',
                'charm': 'clutch',
                'chasse': 'crossbody',
                'city': 'shoulder-bag',
                'clemence': 'wallet-on-chain',
                'clip': 'wallet-on-chain',
                'collier de chien': 'shoulder-bag',
                'commedia dell\'arte': 'clutch',
                'constance': 'constance',
                'courchevel': 'shoulder-bag',
                'crinoline': 'shoulder-bag',
                'cubit': 'shoulder-bag',
                'danse': 'clutch',
                'dogon': 'wallet-on-chain',
                'douglas': 'crossbody',
                'duo': 'crossbody',
                'dynamo': 'shoulder-bag',
                'ecrin': 'clutch',
                'elan': 'shoulder-bag',
                'evelyne': 'crossbody',
                'farandole': 'clutch',
                'fauve': 'shoulder-bag',
                'femmes': 'shoulder-bag',
                'fetiche': 'clutch',
                'garden': 'tote',
                'groom': 'clutch',
                'gypsy': 'crossbody',
                'halzan': 'shoulder-bag',
                'hobo': 'shoulder-bag',
                'horlogerie': 'clutch',
                'hydra': 'shoulder-bag',
                'ideal': 'shoulder-bag',
                'in the loop': 'crossbody',
                'jige': 'clutch',
                'kelly': 'kelly',
                'kelly danse': 'clutch',
                'kelly moove': 'shoulder-bag',
                'kelly sport': 'shoulder-bag',
                'lindy': 'lindy',
                'lutetia': 'shoulder-bag',
                'maline': 'shoulder-bag',
                'malesherbes': 'shoulder-bag',
                'mangeoire': 'picotin',
                'medor': 'clutch',
                'metamorphose': 'shoulder-bag',
                'midi': 'shoulder-bag',
                'mississippi': 'shoulder-bag',
                'modele': 'shoulder-bag',
                'monaco': 'clutch',
                'mosaico': 'shoulder-bag',
                'natte': 'tote',
                'neobain': 'clutch',
                'noeud papillon': 'clutch',
                'nylon': 'crossbody',
                'orange': 'tote',
                'osier': 'tote',
                'paris': 'shoulder-bag',
                'paris-bombay': 'tote',
                'party': 'evening-bag',
                'pegase': 'keepall',
                'pernand': 'shoulder-bag',
                'perrier': 'shoulder-bag',
                'petit': 'mini-bag',
                'picotin': 'picotin',
                'plume': 'shoulder-bag',
                'portefeuille': 'wallet-on-chain',
                'poste': 'crossbody',
                'prelude': 'shoulder-bag',
                'premier': 'shoulder-bag',
                'pythagore': 'shoulder-bag',
                'sac a depeches': 'shoulder-bag',
                'sac a main': 'shoulder-bag',
                'sac a malice': 'shoulder-bag',
                'sac de voyage': 'keepall',
                'sac en deux': 'shoulder-bag',
                'sac flat': 'shoulder-bag',
                'sac hippopotame': 'shoulder-bag',
                'sac kelly': 'kelly',
                'sac mallette': 'keepall',
                'sac plie': 'shoulder-bag',
                'sac porochon': 'picotin',
                'sac trio': 'shoulder-bag',
                'saleya': 'tote',
                'samarcande': 'shoulder-bag',
                'sangle': 'shoulder-bag',
                'savoie': 'shoulder-bag',
                'seconde': 'clutch',
                'shadow': 'shoulder-bag',
                'silk': 'clutch',
                'silk in': 'clutch',
                'silk pocket': 'clutch',
                'slim': 'wallet-on-chain',
                'soie': 'clutch',
                'steeple': 'shoulder-bag',
                'suitcase': 'keepall',
                'tarmac': 'keepall',
                'tassili': 'shoulder-bag',
                'tea time': 'clutch',
                'tempete': 'shoulder-bag',
                'the': 'tote',
                'toile': 'tote',
                'togo': 'shoulder-bag',
                'touch': 'shoulder-bag',
                'trousse': 'clutch',
                'valparaiso': 'tote',
                'verrou': 'shoulder-bag',
                'victoria': 'shoulder-bag',
                'voyage': 'keepall',
                'walden': 'shoulder-bag',
                'waterloo': 'shoulder-bag',
                'watch': 'clutch',
                'wax': 'clutch',
                'wallet': 'wallet-on-chain',
                'wind': 'shoulder-bag',
                'zip': 'wallet-on-chain',
                'zip around': 'wallet-on-chain'
            },
            'gucci': {
                'horsebit': 'horsebit',
                'dionysus': 'dionysus',
                'marmont': 'marmont',
                'jackie': 'jackie',
                'bamboo': 'bamboo',
                'diana': 'diana',
                'tori': 'tori',
                'gg marmont': 'gg-marmont',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'backpack': 'backpack',
                'borsetto': 'shoulder-bag',
                'boston': 'shoulder-bag',
                'paparazzo': 'shoulder-bag',
                'siena': 'shoulder-bag',
                'vanity': 'vanity',
                'padlock': 'shoulder-bag',
                'softbit': 'shoulder-bag',
                'blondie': 'shoulder-bag',
                'bucket': 'crossbody',
                'top handle': 'shoulder-bag',
                'bumbag': 'belt-bag',
                'screener': 'clutch',
                'shift': 'clutch',
                'sneaker': 'clutch',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'fanny pack': 'belt-bag'
            },
            'ysl': {
                'loulou': 'loulou',
                'kate': 'kate',
                'niki': 'niki',
                'puffer': 'puffer',
                'manhattan': 'manhattan',
                'vanity': 'vanity',
                'le 5 à 7': 'le-5-a-7',
                'wallet on chain': 'wallet-on-chain',
                'crossbody': 'crossbody',
                'tote': 'tote',
                'sunset': 'shoulder-bag',
                'lou camera': 'crossbody',
                'camera bag': 'crossbody',
                'college': 'shoulder-bag',
                'monogram': 'shoulder-bag',
                'tribute': 'shoulder-bag',
                'downtown': 'shoulder-bag',
                'uptown': 'shoulder-bag',
                'easy': 'tote',
                'cabas': 'tote',
                'travelling': 'tote',
                'shopping': 'tote',
                'cassandra': 'shoulder-bag',
                'opal': 'shoulder-bag',
                'jamie': 'shoulder-bag',
                'nano': 'mini-bag',
                'tiny': 'mini-bag',
                'mini': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'small': 'mini-bag',
                'soft': 'shoulder-bag',
                'quilted': 'shoulder-bag',
                'embossed': 'shoulder-bag',
                'matelasse': 'shoulder-bag',
                'monogramme': 'shoulder-bag',
                'gold hardware': 'shoulder-bag',
                'silver hardware': 'shoulder-bag',
                'chain': 'wallet-on-chain',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'python': 'shoulder-bag',
                'crocodile': 'shoulder-bag',
                'alligator': 'shoulder-bag',
                'ostrich': 'shoulder-bag',
                'snake': 'shoulder-bag',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'icare': 'tote',
                'amalía': 'shoulder-bag',
                'amalia': 'shoulder-bag',
                'voltaire': 'shoulder-bag',
                'pochon': 'pouch',
                'calypso': 'shoulder-bag',
                'raffia': 'tote',
                'shearling': 'shoulder-bag',
                'box saint': 'shoulder-bag',
                'top handle': 'shoulder-bag',
                'paris vii': 'clutch',
                'evening': 'evening-bag',
                'backpack': 'backpack',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'belt': 'belt-bag'
            },
            'prada': {
                're-edition': 're-edition',
                'nylon': 'nylon',
                'saffiano': 'saffiano',
                'symbol': 'symbol',
                'cleo': 'cleo',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'backpack': 'backpack',
                'shoulder bag': 'shoulder-bag',
                'bonnie': 'shoulder-bag',
                'explore': 'shoulder-bag',
                'enchaine': 'shoulder-bag',
                'tumulte': 'shoulder-bag',
                'dada': 'shoulder-bag',
                'galleria': 'shoulder-bag',
                'mariner': 'crossbody',
                'dangle': 'shoulder-bag',
                'moon': 'shoulder-bag',
                'new galleria': 'shoulder-bag',
                'buckle': 'shoulder-bag',
                'darling': 'shoulder-bag',
                'top handle': 'shoulder-bag',
                'bucket': 'crossbody',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'extra-large': 'tote',
                'extra large': 'tote',
                'leather': 'shoulder-bag',
                'linen': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag'
            },
            'bottega veneta': {
                'cassette': 'cassette',
                'jodie': 'jodie',
                'andiamo': 'andiamo',
                'kalimero': 'kalimero',
                'minidomingo': 'minidomingo',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'shoulder bag': 'shoulder-bag',
                'lauren': 'shoulder-bag',
                'capucines': 'shoulder-bag',
                'ciao ciao': 'crossbody',
                'basket': 'tote',
                'veneta': 'shoulder-bag',
                'mini veneta': 'mini-bag',
                'small veneta': 'mini-bag',
                'medium veneta': 'shoulder-bag',
                'large veneta': 'tote',
                'loop': 'crossbody',
                'mini loop': 'mini-bag',
                'small loop': 'mini-bag',
                'medium loop': 'crossbody',
                'large loop': 'tote',
                'bv': 'shoulder-bag',
                'mini bv': 'mini-bag',
                'small bv': 'mini-bag',
                'medium bv': 'shoulder-bag',
                'large bv': 'tote',
                'belt': 'belt-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'backpack': 'backpack',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag'
            },
            'celine': {
                'triomphe': 'triomphe',
                'ava': 'ava',
                'belt': 'belt',
                'luggage': 'luggage',
                'box': 'box',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'shoulder bag': 'shoulder-bag',
                'multipochette': 'clutch',
                'louise': 'crossbody',
                'bucket': 'crossbody',
                'cabas': 'tote',
                'triangle': 'tote',
                'panier': 'tote',
                'shopper': 'tote',
                'boston': 'shoulder-bag',
                'polly': 'shoulder-bag',
                'teen': 'mini-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'raffia': 'tote',
                'calfskin': 'shoulder-bag',
                'soft': 'shoulder-bag',
                'smooth': 'shoulder-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'backpack': 'backpack',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag'
            },
            'goyard': {
                'saint louis': 'saint-louis',
                'anjou': 'anjou',
                'croissy': 'croissy',
                'belvedere': 'belvedere',
                'tote': 'tote',
                'clutch': 'clutch',
                'rouette': 'shoulder-bag',
                'souple': 'shoulder-bag',
                'rouette souple': 'shoulder-bag',
                'voltaire': 'shoulder-bag',
                'chypre': 'shoulder-bag',
                'hobo': 'shoulder-bag',
                'petit hobo': 'mini-bag',
                'small hobo': 'mini-bag',
                'medium hobo': 'shoulder-bag',
                'large hobo': 'tote',
                'charm': 'clutch',
                'mini charm': 'clutch',
                'small charm': 'clutch',
                'medium charm': 'shoulder-bag',
                'large charm': 'tote',
                'fleming': 'shoulder-bag',
                'mini fleming': 'mini-bag',
                'small fleming': 'mini-bag',
                'medium fleming': 'shoulder-bag',
                'large fleming': 'tote',
                'bourget': 'backpack',
                'mini bourget': 'mini-bag',
                'small bourget': 'mini-bag',
                'medium bourget': 'backpack',
                'large bourget': 'backpack',
                'caban': 'tote',
                'mini caban': 'tote',
                'small caban': 'tote',
                'medium caban': 'tote',
                'large caban': 'tote',
                'tote bag': 'tote',
                'shoulder bag': 'shoulder-bag',
                'crossbody': 'crossbody',
                'backpack': 'backpack',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'evening': 'evening-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag'
            },
            'loewe': {
                'puzzle': 'puzzle',
                'hammock': 'hammock',
                'gate': 'gate',
                'balloon': 'balloon',
                'puzzle fold': 'puzzle-fold',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'shoulder bag': 'shoulder-bag',
                'amazona': 'shoulder-bag',
                'anagram': 'tote',
                'flamenco': 'pouch',
                'ola': 'shoulder-bag',
                'madrid': 'shoulder-bag',
                'pebble': 'crossbody',
                'paseo': 'shoulder-bag',
                'squeeze': 'shoulder-bag',
                'bucket': 'crossbody',
                'basket': 'tote',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'backpack': 'backpack'
            },
            'balenciaga': {
                'city': 'city',
                'hourglass': 'hourglass',
                'bazar': 'bazar',
                'duffle': 'duffle',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'bel air': 'shoulder-bag',
                'hobo': 'shoulder-bag',
                'carry all': 'tote',
                'rodeo': 'shoulder-bag',
                'crush': 'shoulder-bag',
                'chain': 'wallet-on-chain',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'backpack': 'backpack',
                'shoulder bag': 'shoulder-bag'
            },
            'miumiu': {
                'wander': 'wander',
                'arcadie': 'arcadie',
                'muse': 'muse',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'aventure': 'shoulder-bag',
                'ivy': 'shoulder-bag',
                'top-handle': 'shoulder-bag',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'regular': 'shoulder-bag',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'backpack': 'backpack',
                'shoulder bag': 'shoulder-bag',
                'matelasse': 'shoulder-bag'
            },
            'fendi': {
                'baguette': 'baguette',
                'peekaboo': 'peekaboo',
                'first': 'first',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'spy': 'shoulder-bag',
                'by the way': 'shoulder-bag',
                'fendigraphy': 'shoulder-bag',
                'kan i': 'shoulder-bag',
                'runaway': 'tote',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'backpack': 'backpack',
                'shoulder bag': 'shoulder-bag'
            },
            'burberry': {
                'kensington': 'kensington',
                'check': 'check',
                'tote': 'tote',
                'crossbody': 'crossbody',
                'paddy': 'shoulder-bag',
                'freddie': 'shoulder-bag',
                'lola': 'shoulder-bag',
                'vertical': 'shoulder-bag',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'backpack': 'backpack',
                'shoulder bag': 'shoulder-bag'
            },
            'loro piana': {
                'extra pocket': 'extra-pocket',
                'sesia': 'sesia',
                'tote': 'tote',
                'extra bag': 'shoulder-bag',
                'bag': 'shoulder-bag',
                'handbag': 'shoulder-bag',
                'mini': 'mini-bag',
                'small': 'mini-bag',
                'medium': 'shoulder-bag',
                'large': 'tote',
                'leather': 'shoulder-bag',
                'canvas': 'tote',
                'denim': 'shoulder-bag',
                'suede': 'shoulder-bag',
                'velvet': 'evening-bag',
                'fur': 'evening-bag',
                'wallet': 'wallet-on-chain',
                'card holder': 'wallet-on-chain',
                'long wallet': 'wallet-on-chain',
                'coin purse': 'wallet-on-chain',
                'key holder': 'wallet-on-chain',
                'passport cover': 'wallet-on-chain',
                'phone case': 'clutch',
                'lipstick case': 'clutch',
                'glasses case': 'clutch',
                'bag charm': 'clutch',
                'scarf': 'clutch',
                'pouch': 'pouch',
                'clutch': 'clutch',
                'evening': 'evening-bag',
                'belt bag': 'belt-bag',
                'bumbag': 'belt-bag',
                'fanny pack': 'belt-bag',
                'backpack': 'backpack',
                'shoulder bag': 'shoulder-bag',
                'crossbody': 'crossbody'
            },
            'givenchy': {
                'antigona': 'antigona',
                'nightingale': 'nightingale'
            }
        }

        # 获取对应品牌的规则
        brand_rules = subcategory_rules.get(brand_lower, {})

        # 按优先级匹配（长的关键词优先）
        for keyword, subcat in sorted(brand_rules.items(), key=lambda x: -len(x[0])):
            if keyword in name_lower:
                return subcat

        # 如果没有匹配到品牌特定规则，使用通用规则
        generic_rules = {
            'backpack': 'backpack',
            'crossbody': 'crossbody',
            'shoulder bag': 'shoulder-bag',
            'tote': 'tote',
            'clutch': 'clutch',
            'wallet': 'wallet-on-chain',
            'mini': 'mini-bag',
            'belt bag': 'belt-bag'
        }

        for keyword, subcat in generic_rules.items():
            if keyword in name_lower:
                return subcat

        # 都没匹配到，返回other
        return 'other'

    def fix_product_file(self, file_path: Path) -> bool:
        """修复单个产品文件"""
        try:
            # 读取产品数据
            with open(file_path, 'r', encoding='utf-8') as f:
                products = json.load(f)

            # 为每个产品添加subcategory字段
            updated_products = []
            for product in products:
                # 提取子分类
                subcategory = self.extract_subcategory(
                    product.get('name', ''),
                    product.get('brand', '')
                )

                # 添加subcategory字段
                product['subcategory'] = subcategory
                updated_products.append(product)

                self.processed_count += 1
                print(f"[OK] Processed: {product['brand']} - {product['name']} -> {subcategory}")

            # 保存更新后的数据
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(updated_products, f, ensure_ascii=False, indent=2)

            return True

        except Exception as e:
            print(f"[ERROR] Error processing file {file_path}: {str(e)}")
            self.error_count += 1
            return False

    def fix_index_file(self, file_path: Path) -> bool:
        """修复索引文件"""
        try:
            # 读取索引数据
            with open(file_path, 'r', encoding='utf-8') as f:
                products = json.load(f)

            # 为每个产品添加subcategory字段
            updated_products = []
            for product in products:
                # 提取子分类
                subcategory = self.extract_subcategory(
                    product.get('name', ''),
                    product.get('brand', '')
                )

                # 添加subcategory字段
                product['subcategory'] = subcategory
                updated_products.append(product)

            # 保存更新后的数据
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(updated_products, f, ensure_ascii=False, indent=2)

            return True

        except Exception as e:
            print(f"[ERROR] Error processing index file {file_path}: {str(e)}")
            self.error_count += 1
            return False

    def run(self):
        """运行修复流程"""
        print("Starting to fix existing product data, adding subcategory field...")

        # 处理产品文件
        product_files = list(self.data_dir.glob('products-*.json'))
        print(f"\n[FILES] Found {len(product_files)} product files")

        for product_file in product_files:
            print(f"\n[PROCESS] Processing file: {product_file.name}")
            if self.fix_product_file(product_file):
                print(f"[OK] Successfully updated {product_file.name}")

        # 处理索引文件
        index_files = list(self.data_dir.glob('index-*.json'))
        print(f"\n[INDEX] Found {len(index_files)} index files")

        for index_file in index_files:
            print(f"\n[PROCESS] Processing index file: {index_file.name}")
            if self.fix_index_file(index_file):
                print(f"[OK] Successfully updated {index_file.name}")

        # 处理全局搜索索引
        search_index = self.data_dir / 'search-index.json'
        if search_index.exists():
            print(f"\n[SEARCH] Processing global search index: {search_index.name}")
            if self.fix_index_file(search_index):
                print(f"[OK] Successfully updated {search_index.name}")

        print(f"\n[COMPLETE] Fix completed!")
        print(f"[STATS] Processed {self.processed_count} products")
        print(f"[ERRORS] {self.error_count} errors")

if __name__ == "__main__":
    fixer = SubcategoryFixer()
    fixer.run()